<?php
//==============insert values into $table5===================
$stable5= "INSERT INTO ".$table5."(
`fk_patId`,`farmer_code`,
`coffee_acreage`,`coffee_mapped`,
`coffee_improved_seeds`,`coffee_improved_acreage`,
`coffee_improved_acreage_mapped`,`coffee_improved_cost`,
`coffee_seed_supplier`,`coffee_seed_supplier_other`,
`coffee_benefits`,`coffee_benefits_other`,
`coffee_fetilizer_use`,`coffee_acreage_fertilizer`,
`coffee_fertilizer_cost`,`coffee_fertilizer_supplier`,
`coffee_fertilizer_supplier_other`,`coffee_fertilizer_benefits`,
`coffee_fertilizer_benefits_other`,`coffee_chemical_use`,
`coffee_chemical_acreage`,`coffee_chemical_acreage_mapped`,
`coffee_chemical_cost`,`coffee_chemical_supplier`,
`coffee_chemical_supplier_other`,`coffee_chemical_benefits`,
`coffee_chemical_benefits_other`,`coffee_mgt_practices`,
`coffee_mgt_practices_acreage`,`coffee_mgt_practices_acreage_mapped`,
`coffee_cost_ict`,`coffee_ict_supplier`,
`coffee_ict_supplier_other`,`coffee_mgt_benefits`,
`coffee_mgt_benefits_other`,`coffee_machinery_use`,
`coffee_machinery_acreage`,`coffee_machinery_acreage_mapped`,
`coffee_machinery_cost`,`coffee_machinery_supplier`,
`coffee_machinery_supplier_other`,`coffee_machinery_benefits`,
`coffee_machinery_benefits_other`,`coffee_harvested`,
`coffee_sold`,`coffee_sold_price`,
`coffee_harvest_loss`,`msg_at_readtime`,
`readtime`) 
VALUES ('".$fk_patId."','".$farmer_code."',
'".$coffee_acreage."','".$coffee_acreage_mappped."',
'".$coffee_improved_seeds."','".$coffee_improved_acreage."',
'".$coffee_improved_acreage_mapped."','".$coffee_improved_cost."',
'".$coffee_seed_supplier."','".$coffee_seed_supplier_other."',
'".$coffee_benefits."','".$coffee_benefits_other."',
'".$coffee_fetilizer_use."','".$coffee_acreage_fertilizer."',
'".$coffee_fertilizer_cost."','".$coffee_fertilizer_supplier."',
'".$coffee_fertilizer_supplier_other."','".$coffee_fertilizer_benefits."',
'".$coffee_fertilizer_benefit_other."','".$coffee_chemical_use."',
'".$coffee_chemical_acreage."','".$coffee_chemical_acreage_mapped."',
'".$coffee_chemical_cost."','".$coffee_chemical_supplier."',
'".$coffee_chemical_supplier_other."','".$coffee_chemical_benefits."',
'".$coffee_chemical_benefits_other."','".$coffee_mgt_practices."',
'".$coffee_mgt_practices_acreage."','".$coffee_mgt_practices_acreage_mapped."',
'".$coffee_cost_ict."','".$coffee_ict_supplier."',
'".$coffee_ict_supplier_other."','".$coffee_mgt_benefits."',
'".$coffee_mgt_benefits_other."','".$coffee_machinery_use."',
'".$coffee_machinery_acreage."','".$coffee_machinery_acreage_mapped."',
'".$coffee_machinery_cost."','".$coffee_machinery_supplier."',
'".$coffee_machinery_supplier_other."','".$coffee_machinery_benefits."',
'".$coffee_machinery_benefits_other."','".$coffee_harvested."',
'".$coffee_sold."','".$coffee_sold_price."',
'".$coffee_harvest_lost."','".$msg_at_readtime."',
'".$timestamp."')";
//$e=mysql_query($stable5, $connect );
//============== end of insert values into $table5===================